[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
open_cookie = "CookK2qhhmsrfWH3oSTZMxmFC4aV5E7fBquf2AX6TqBm"

[programs.devnet]
open_cookie = "CookK2qhhmsrfWH3oSTZMxmFC4aV5E7fBquf2AX6TqBm"

[programs.mainnet]
open_cookie = "CookK2qhhmsrfWH3oSTZMxmFC4aV5E7fBquf2AX6TqBm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"

[hooks]
